In [1]:
!pip install neo4j
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: neo4j in /home/vashinav/.local/lib/python3.12/site-packages (5.25.0)
Requirement already satisfied: pytz in /home/vashinav/anaconda3/lib/python3.12/site-packages (from neo4j) (2024.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/vashinav/anaconda3/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /home/vashinav/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/vashinav/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/vashinav/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/vashinav/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /home/vashinav/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
import json
import requests
from neo4j import GraphDatabase

In [4]:
url = 'https://stapi.co/api/v1/rest/episode/search'

params = {
    'pageSize': 50 ,
    'pageNumber': 1
}

episodes = pd.DataFrame()
response = requests.get(url, params=params)
totalPages = int(response.json()['page']['totalPages'])

for i in range(1, int(totalPages)):
    params['pageNumber'] = i
    response = requests.get(url, params=params)
    epis = pd.json_normalize(response.json(), 'episodes')
    epis = epis[epis['series.uid'] == 'SEMA0000073238']
    epis = epis [['uid', 'title', 'yearFrom', 'yearTo', 'usAirDate']]
    # print(epis)
    episodes = pd.concat([episodes, epis])

In [14]:
episodes

,uid,title,yearFrom,yearTo,usAirDate
4,EPMA0000001105,Babel,2369.0,2369.0,1993-01-24
6,EPMA0000000999,"Badda-Bing, Badda-Bang",2375.0,2375.0,1999-02-24
8,EPMA0000000924,Bar Association,2372.0,2372.0,1996-02-19
12,EPMA0000000851,Battle Lines,2369.0,2369.0,1993-04-25
15,EPMA0000000964,Behind the Lines,2374.0,2374.0,1997-10-20
...,...,...,...,...,...
36,EPMA0000001006,When It Rains...,2375.0,2375.0,1999-05-05
42,EPMA0000000873,Whispers,2370.0,2370.0,1994-02-06
44,EPMA0000000972,Who Mourns for Morn?,2374.0,2374.0,1998-02-04
3,EPMA0000000977,Wrongs Darker Than Death or Night,2374.0,2374.0,1998-03-28
8,EPMA0000000967,You Are Cordially Invited,2374.0,2374.0,1997-11-10

In [3]:
URI = "neo4j://localhost:7687"
AUTH = ("neo4j", "password")

Connection established.

In [31]:
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    driver.verify_connectivity()
    print("established connection")
    with driver.session(database='neo4j') as session:
        for index, row in episodes.iterrows():
            result = session.run(
                "CREATE (:Episode {uid: $uid, title: $title, yearFrom: $yearFrom, yearTo: $yearTo, usAirDate: $usAirDate})",
                uid = row['uid'],
                title = row['title'],
                yearFrom = row['yearFrom'],
                yearTo = row['yearTo'],
                usAirDate = row['usAirDate'],
                database_ = "neo4j",
            )
            summary = result.consume()
            print("Created {nodes_created} nodes in {time} ms.".format(
                nodes_created=summary.counters.nodes_created,
                time=summary.result_available_after
            ))

established connection
Created 1 nodes in 2 ms.
Created 1 nodes in 28 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 4 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 3 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 3 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 2 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 0 ms.
Created 1 nodes in 0 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 1 ms.
Created 1 nodes in 0 ms.
Created 1 nodes in 1 ms.

Created 1 nodes in 67 ms.

/tmp/ipykernel_249851/2429642574.py:1: DeprecationWarning: Using a driver after it has been closed is deprecated. Future versions of the driver will raise an error.
  summary = driver.execute_query(